repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
      - id: check-json
      - id: name-tests-test

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
          [
            --max-line-length=100,
            "--per-file-ignores=__init__.py:F401",
            "--ignore=E203,E402,E501,W503,F821,C901",
          ]

  - repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=80]
